### ISSUE TITLE
Multiple Chips with Same Value

### ISSUE THREAD

**Issue by Maaayank** [TheAlphamerc/flutter_plugin_filter_list#13]
**Describe the bug**
Using this plugin I am trying to group results  based on locations, but for every repeated Location the plugin treats it as a different entity, hence shows a different chip for the same.

**To Reproduce**
A list with  objects having fields : id (string: unique), name: (string: unique), location (string: repeated). 
I want to use the filter on location.

**Expected behavior**
The plugin should group all location objects together and show the result

**Screenshots**
![image](https://user-images.githubusercontent.com/35776774/123972362-670cfd80-d9d8-11eb-8eb5-c2077630f776.png)

**Additional context**
The example App provided does not have repeated values in the array, is this the default behavior of the plugin. 
If there is anyway I can group similar objects together using this plugin then help me out.

**Comment by TheAlphamerc** [comment]
@Maaayank  Your issue looks like similar to  [this](https://github.com/TheAlphamerc/flutter_plugin_filter_list/issues/9) thread. Have a look at it.
