### ISSUE TITLE
Change the font size of "All", "Reset" and "Apply" button

### ISSUE THREAD

**Issue by konewltd** [TheAlphamerc/flutter_plugin_filter_list#2]
I wish the font size of "All", "Reset" and "Apply" button can be adjusted. Right now, I think it is too large and will cause overflow on small screen device.

**Comment by karamba121** [comment]
The text of this buttons can be customized, too

**Comment by josedavidrp** [comment]
> The text of this buttons can be customized, too

Do you mean its possible or that it should be possible? Because I found no way of doing it

**Comment by mozochek** [comment]
I think good feature is make this buttons full customizible with default values, so if you need to customize them - you can, if you don't need - default values will be applied.

**Comment by muhammadsaad-ak** [comment]
> The text of this buttons can be customized, too

How???

**Comment by TheAlphamerc** [comment]
Hey Guys, the feature is now available in package version 0.0.8, The controls buttons are fully customizable.
