### ISSUE TITLE
Customise close button on a dialog

### ISSUE THREAD

**Issue by bparol** [TheAlphamerc/flutter_plugin_filter_list#20]
**Is your feature request related to a problem? Please describe.**
It would be good to add option to customise close button appearance in order to make it consistent with the rest of application. There is already an option to customise close icon color, however it's not currently possible to change the icon itself.

**Describe the solution you'd like**
A builder for delivering the button would be perfect.

**Comment by TheAlphamerc** [comment]
Thanks for the suggestion. I'll add close icon customization feature in the next release.
