### ISSUE TITLE
Option to Remove The Shadow in FilterList Content Area

### ISSUE THREAD

**Issue by AathifMahir** [TheAlphamerc/flutter_plugin_filter_list#21]
**Is your feature request related to a problem? Please describe.**
Currently Filterlist does have default shadow in Content Area That doesn't Go with My Apps Design Language, Please have an Option to Disable That

**Describe the solution you'd like**
Add Boolean to Turn that Default Shadow ON and OFF, for ex HideContentAreaShadow

**Additional context**

Here's Image that represent Default Shadow on Content Area

![Inkedscreenshot_6](https://user-images.githubusercontent.com/17165402/145396443-016d47ec-e9e0-4c04-b8af-76d668d8e28c.jpg)

**Comment by TheAlphamerc** [comment]
Thanks @AathifMahir to raise this issue. I'll fix this in the next update.

**Comment by AathifMahir** [comment]
Sure thing @TheAlphamerc
