### ISSUE TITLE
Disabling "All" and "Reset" buttons

### ISSUE THREAD

**Issue by guplem** [TheAlphamerc/flutter_plugin_filter_list#24]
**Is your feature request related to a problem? Please describe.**
It would be very nice to be able to remove the "all" and "reset" buttons. 

**Describe the solution you'd like**
A parameter in the constructor to allow you to remove the "all" and "reset" buttons if desired. If removed, the "Accept" button should be the only one remaining and could be automatically centred to the bottom middle.

**Describe alternatives you've considered**
I have tried removing the text from the button (using "resetButtonText" and "allButtonText"), but it's still showing the buttons. Maybe giving an empty string ("") could disable it.

**Additional context**
I am using the widget as a tag selector while in the creation of elements for my app, and it makes no sense to have the "all" button, I wouldn't want the users to set all the tags to a new element, usually they should add only 2-3.

**Comment by TheAlphamerc** [comment]
@guplem Thanks for the suggestion. I'll add the boolean parameter to hide `All` and `Reset` buttons. The new version of the package will be rolled out soon and make sure to read the documentation and [Changelog.md](https://github.com/TheAlphamerc/flutter_plugin_filter_list/blob/master/CHANGELOG.md) before updating the package because the new version of the package will contain some breaking change related to  filter dialog theme.

**Comment by TheAlphamerc** [comment]
@guplem I have added a `controlButtons` parameter in the widget and its type is `List<ControlButtonType>`.
`ControlByttonType` is an enum that consists `All` and `Reset`.

``` dart
// Display 'All` button alongside `Apply` button
controlButtons: [ContolButtonType.All]
```

``` dart
// Display 'Reset` button alongside `Apply` button
controlButtons: [ContolButtonType.Reset]
```

>If you want to display all buttons `(All, Reset, Apply)` then don't use `controlButtons` parameter or pass null value.

**Comment by TheAlphamerc** [comment]
@guplem New version is available on pub.dev. Let me know if you face any issue.

**Comment by guplem** [comment]
Thanks for the update!

It seems to work flawlessly, and it has many new features that will be highly appreciated!

The slightly new design is cool too, thank you for your time!
