### ISSUE TITLE
How to Add subtitle

### ISSUE THREAD

**Issue by mushtaq99** [TheAlphamerc/flutter_plugin_filter_list#27]
**as the library support single item in choiceChipLabel **
how to add subtitle in  choiceChipLabel if data has subtitle [...]

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by TheAlphamerc** [comment]
@mushtaq99 you can use `choiceChipBuilder` to build custom choice chip and doing do you can add what you need to display there. 
#### An example of how to use `choiceChipBuilder`.

```dart
choiceChipBuilder: (context, item, isSelected) {
    return Container(
       padding: EdgeInsets.symmetric(horizontal: 16, vertical: 12),
        margin: EdgeInsets.symmetric(horizontal: 10, vertical: 10),
        decoration: BoxDecoration(
           border: Border.all(
           color: isSelected! ? Colors.blue[300]! : Colors.grey[300]!,
          )),
        child: Column(
           children: [Text('Title text'), Text('Subtitle text')],
         ),
      );
 }
```
