### ISSUE TITLE
Select only one option [feature]

### ISSUE THREAD

**Issue by Madanraj1** [TheAlphamerc/flutter_plugin_filter_list#3]
hey there ,
the package is all good , thanks for that,
i was hoping if you can add one more feature that would be great help
--------------The Feature----------------
the user can select the multiple options right 
can you add something like the user can select only one option 
when he tries to select other option then other option should be automatically deselected 
---basically user can select only one option-------

**Comment by ikerfah** [comment]
@TheAlphamerc Do you have any plans to work more on this package ? i may this feature later, so i prefer to make a pull request for this package instead of making something similar from scratch. What do you think ?

**Comment by TheAlphamerc** [comment]
Currently, I have no plan for it. I will appreciate it if you can contribute to this package.

**Comment by TheAlphamerc** [comment]
> hey there ,
> the package is all good , thanks for that,
> i was hoping if you can add one more feature that would be great help
> --------------The Feature----------------
> the user can select the multiple options right
> can you add something like the user can select only one option
> when he tries to select other option then other option should be automatically deselected
> ---basically user can select only one option-------

Hi @Madanraj1 , The feature you are asked for is introduced in package version 0.0.8.
