### ISSUE TITLE
Remove bottom Bar Or just remove Apply button.

### ISSUE THREAD

**Issue by Tristannos** [TheAlphamerc/flutter_plugin_filter_list#37]
i just don't want the apply button but i cant get rid of it.

The most easy way is just inculde the apply button in the "controlButtons" list.

Or just remove the whole bar together because i dont want any buttons.

![Screenshot 2022-12-05 at 10 19 18](https://user-images.githubusercontent.com/55278228/205600242-6afa7975-79f0-4460-bf1a-2e73ed0c3bee.png)

**Comment by TheAlphamerc** [comment]
Hi @Tristannos, Without Apply button how selected items will reflect back to UI?

**Comment by Tristannos** [comment]
I wil overwrite my list with the list in the validateSelectedItem(list, item){

selectedUsers = list:

} function

**Comment by Tristannos** [comment]
But i already succeeded in removing the button.
With => height: 0

<img width="423" alt="SCR-20221207-elx" src="https://user-images.githubusercontent.com/55278228/206141512-2b3905a5-3f0a-4651-b3e8-31f204553a13.png">
