### ISSUE TITLE
Selected chip color

### ISSUE THREAD

**Issue by Shouqsb** [TheAlphamerc/flutter_plugin_filter_list#7]
selectedTextBackgroundColor Feature unavailable in 0.0.8 update  
How can change the selected chips color ??

**Comment by TheAlphamerc** [comment]
Yes, `selectedTextBackgroundColor ` is available in v0.08.  [Reference](https://github.com/TheAlphamerc/flutter_plugin_filter_list/blob/b54e0ff374994bd0128da13e7bc19d471dc69d15/lib/src/widget/choice_chip_widget.dart#L21)
