### ISSUE TITLE
Merging Duplicate Items in Choice Chip into 1

### ISSUE THREAD

**Issue by AathifMahir** [TheAlphamerc/flutter_plugin_filter_list#9]
**Is your feature request related to a problem? Please describe.**

currently, If we have duplicates in the choice chip, filter list still shows the duplicate.

**Describe the solution you'd like**

it would be great if we have option to merge duplicate items into 1.

**Comment by AathifMahir** [comment]
@TheAlphamerc Hi, I'm waiting for your take on this issue, will be waiting for your reply

Thanks

**Comment by TheAlphamerc** [comment]
Hi @AathifMahir, If you don't want to display duplicates item in choice chip then you can remove those duplicate items from list before providing the list to the  `FilterListDialog`.

**Comment by AathifMahir** [comment]
> Hi @AathifMahir, If you don't want to display duplicates item in choice chip then you can remove those duplicate items from list before providing the list to the  `FilterListDialog`. 

I have tried that since the choice chip is built based on the data that's available in the list based on index, I can't seem to remove that, i need to find a way to merge data from choice chip after the data is built and merge those indexes

**Comment by TheAlphamerc** [comment]
Can you share the sample list data that you are using ?

**Comment by AathifMahir** [comment]
@TheAlphamerc you can check this video for better understanding on the scenario that I'm currently facing

https://user-images.githubusercontent.com/17165402/122901691-64bcfa80-d36b-11eb-89b1-bc8eef1c283c.MOV

**Comment by TheAlphamerc** [comment]
I didn't understand what you trying to say through video. Help me understanding the issue, I'll try to find a way to resolve this.

**Comment by AathifMahir** [comment]
> I didn't understand what you trying to say through video. Help me understanding the issue, I'll try to find a way to resolve this.

Accessing the data using provider with a modal for Productsdata, the datas were pulled from firestore based on the attributes,

By the all the single data has the status eg: halal lv1, halal lv2, haram lv1, etc..

The status is the things that used for data filtering that built inside the chicechip, since status is available in every single object, the all single status available in the data getaways built inside the choicechip based on index on data,

Now, i need to merge those duplicates status into single item in choicechip

**Comment by TheAlphamerc** [comment]
What you are passing the   `FilterListDialog` ?
I mean `List<String>` or `List<Object>`

**Comment by AathifMahir** [comment]
> What you are passing to the `FilterListDialog` ?
> 
> I mean `List<String>` or `List<Object>` 

I'm passing List<ProductModel> into FilterListDialog

**Comment by TheAlphamerc** [comment]
What type of List you are passing ?

**Comment by AathifMahir** [comment]
> What type of List you are passing ?

List with ProductModel as data

**Comment by TheAlphamerc** [comment]
That full be helpfull.

**Comment by AathifMahir** [comment]
@TheAlphamerc Here's some code samples for better understanding of structure

![Screenshot 2021-06-22 162702](https://user-images.githubusercontent.com/17165402/122913226-cfbffe80-d376-11eb-9a08-686515833220.png)
![Screenshot 2021-06-22 162844](https://user-images.githubusercontent.com/17165402/122913336-ee25fa00-d376-11eb-841c-ca2eb74b36f7.png)

**Comment by AathifMahir** [comment]
Here's some images on ProductModel

![Screenshot 2021-06-22 163418](https://user-images.githubusercontent.com/17165402/122914008-d1d68d00-d377-11eb-8804-d59b256f7041.png)
![Screenshot 2021-06-22 163452](https://user-images.githubusercontent.com/17165402/122914021-d438e700-d377-11eb-9d9e-cdb79e28e552.png)

**Comment by TheAlphamerc** [comment]
@AathifMahir do share the code of `_openFilterDialog` method instead of screenshot.

**Comment by AathifMahir** [comment]
@TheAlphamerc Here you go

void _openFilterDialog() async {
    await FilterListDialog.display<ProductModel>(
      context,
      listData: widget.product,
      selectedListData: selectedUserList,
      height: 480,
      // headlineText: "Select Users",
      searchFieldHintText: "Search Here",
      choiceChipLabel: (item) {
        return item!.status;
      },
      hideCloseIcon: true,
      hideheader: true,
      hideHeaderText: true,
      hideSearchField: true,
      backgroundColor: Theme.of(context).colorScheme.background,
      applyButonTextBackgroundColor: Theme.of(context).colorScheme.primary,
      selectedTextBackgroundColor: Theme.of(context).colorScheme.primary,
      borderRadius: MySize.size5!,
      controlButtonTextStyle: Theme.of(context).textTheme.subtitle2,
      applyButtonTextStyle: Theme.of(context).textTheme.subtitle2,
      unselectedTextbackGroundColor: Theme.of(context).disabledColor,
      controlContainerDecoration: BoxDecoration(
        borderRadius: BorderRadius.all(Radius.circular(MySize.size3!))
      ),
      // buttonRadius: MySize.size5!,
      validateSelectedItem: (list, val) {
        return list!.contains(val);
      },

      onItemSearch: (list, text) {
        if (list != null) {
          if (list.any((element) =>
              element.status!.toLowerCase().contains(text.toLowerCase()))) {
            /// return list which contains matches
            return list
                .where((element) =>
                element.status!.toLowerCase().contains(text.toLowerCase()))
                .toList();
          }
        }

        return [];
      },

      onApplyButtonClick: (list) {
        setState(() {
          selectedUserList = List.from(list!);
        });
        // Navigator.pop(context);
      },

      /// uncomment below code to create custom choice chip
       choiceChipBuilder: (context, item, isSelected) {
          // return Container(
          //   padding: EdgeInsets.symmetric(horizontal: 16, vertical: 12),
          //   margin: EdgeInsets.symmetric(horizontal: 10, vertical: 10),
          //   decoration: BoxDecoration(
          //       border: Border.all(
          //     color: isSelected! ? Colors.blue[300]! : Colors.grey[300]!,
          //   )),
          //   child: Text(
          //     item.status,
          //     style: TextStyle(
          //         color: isSelected ? Colors.blue[300] : Colors.grey[300]),
          //   ),
          // );
         return Container(
             padding: EdgeInsets.symmetric(horizontal: MySize.size10, vertical: MySize.size10),
             margin: EdgeInsets.symmetric(horizontal: MySize.size10, vertical: MySize.size10),
           decoration: BoxDecoration(
             borderRadius: BorderRadius.all(Radius.circular(MySize.size3!)),
             color: isSelected! ? Theme.of(context).colorScheme.primary : Theme.of(context).disabledColor,
           ),
             child: Text(
           item!.status,
               style: AppTheme.getTextStyle(Theme.of(context).textTheme.subtitle2),
         )
         );
      },
    );
  }

**Comment by TheAlphamerc** [comment]
@AathifMahir Before passing the all data list to the `FilterListDialog` remove duplicate elements. Have a look on below code.

```dart
late List<ProductModel> selectedUserList = [];

void _openFilterDialog() async {
  
   /// List of all products
    List<ProductModel> list = widget.product;
  
    var uniqueList = list.map((e) => e.status).toSet();
   
   /// Remove duplicate products having same uniqueTempList
    list.retainWhere((x) => uniqueList.remove(x.status));

    /// List of all selected products
    List<ProductModel> tempSelectedList = selectedUserList;
   
     if(selectedUserList != null and selectedUserList.isNotEmpty){
       var uniqueTempList = tempSelectedList.map((e) => e.status).toSet();
   
        /// Remove duplicate selected products having same 
        tempSelectedList.retainWhere((x) => uniqueTempList.remove(x.status));
      }
   


    await FilterListDialog.display<ProductModel>(
       context,
       listData:list,
       selectedListData: tempSelectedList,
       height: 480,
    
       searchFieldHintText: "Search Here",
       choiceChipLabel: (item) {
          return item!.status;
        },
       validateSelectedItem: (list, val) {
          return list!.contains(val);
       },
       onApplyButtonClick: (list) {
          widget.product.forEach((element) {
             if (list.any((model) => model.status == element.status)) {
               selectedUserList.add(element);
             }
            });
          setState(() {  });
           // Navigator.pop(context);
        },

       /// uncomment below code to create custom choice chip
       choiceChipBuilder: (context, item, isSelected) {
          return Container(
             padding: EdgeInsets.symmetric(
                 horizontal: MySize.size10, vertical: MySize.size10),
             margin: EdgeInsets.symmetric(
                 horizontal: MySize.size10, vertical: MySize.size10),
             decoration: BoxDecoration(
               borderRadius: BorderRadius.all(Radius.circular(MySize.size3!)),
                  color: isSelected!
                    ? Theme.of(context).colorScheme.primary
                    : Theme.of(context).disabledColor,
               ),
              child: Text(
                item!.status,
                 style:
                  AppTheme.getTextStyle(Theme.of(context).textTheme.subtitle2),
            ));
       },
    );
  }
```

**Comment by AathifMahir** [comment]
> @AathifMahir Before passing the all data list to the `FilterListDialog` remove duplicate elements. Have a look on below code.
> 
> ```dart
> late List<ProductModel> selectedUserList = [];
> 
> void _openFilterDialog() async {
>   
>    /// List of all products
>     List<ProductModel> list = widget.product;
>   
>     var uniqueList = list.map((e) => e.status).toSet();
>    
>    /// Remove duplicate products having same uniqueTempList
>     list.retainWhere((x) => uniqueList.remove(x.status));
> 
>     /// List of all selected products
>     List<ProductModel> tempSelectedList = selectedUserList;
>    
>      if(selectedUserList != null and selectedUserList.isNotEmpty){
>        var uniqueTempList = tempSelectedList.map((e) => e.status).toSet();
>    
>         /// Remove duplicate selected products having same 
>         tempSelectedList.retainWhere((x) => uniqueTempList.remove(x.status));
>       }
>    
> 
> 
>     await FilterListDialog.display<ProductModel>(
>        context,
>        listData:list,
>        selectedListData: tempSelectedList,
>        height: 480,
>     
>        searchFieldHintText: "Search Here",
>        choiceChipLabel: (item) {
>           return item!.status;
>         },
>        validateSelectedItem: (list, val) {
>           return list!.contains(val);
>        },
>        onApplyButtonClick: (list) {
>           widget.product.forEach((element) {
>              if (list.any((model) => model.status == element.status)) {
>                selectedUserList.add(element);
>              }
>             });
>           setState(() {  });
>            // Navigator.pop(context);
>         },
> 
>        /// uncomment below code to create custom choice chip
>        choiceChipBuilder: (context, item, isSelected) {
>           return Container(
>              padding: EdgeInsets.symmetric(
>                  horizontal: MySize.size10, vertical: MySize.size10),
>              margin: EdgeInsets.symmetric(
>                  horizontal: MySize.size10, vertical: MySize.size10),
>              decoration: BoxDecoration(
>                borderRadius: BorderRadius.all(Radius.circular(MySize.size3!)),
>                   color: isSelected!
>                     ? Theme.of(context).colorScheme.primary
>                     : Theme.of(context).disabledColor,
>                ),
>               child: Text(
>                 item!.status,
>                  style:
>                   AppTheme.getTextStyle(Theme.of(context).textTheme.subtitle2),
>             ));
>        },
>     );
>   }
> ```

@TheAlphamerc Sorry, You must've misunderstood. I only need to remove duplicate status not the products. I need to have all the products show as before whenever filter a status like Halal Lv1, that means all the products has that status should be shown on listview.

**Comment by TheAlphamerc** [comment]
> @AathifMahir Before passing the all data list to the `FilterListDialog` remove duplicate elements. Have a look on below code.
> 
> ```dart
> late List<ProductModel> selectedUserList = [];
> 
> void _openFilterDialog() async {
>   
>    /// List of all products
>     List<ProductModel> list = widget.product;
>   
>     var uniqueList = list.map((e) => e.status).toSet();
>    
>    /// Remove duplicate products having same uniqueTempList
>     list.retainWhere((x) => uniqueList.remove(x.status));
> 
>     /// List of all selected products
>     List<ProductModel> tempSelectedList = selectedUserList;
>    
>      if(selectedUserList != null and selectedUserList.isNotEmpty){
>        var uniqueTempList = tempSelectedList.map((e) => e.status).toSet();
>    
>         /// Remove duplicate selected products having same 
>         tempSelectedList.retainWhere((x) => uniqueTempList.remove(x.status));
>       }
>    
> 
> 
>     await FilterListDialog.display<ProductModel>(
>        context,
>        listData:list,
>        selectedListData: tempSelectedList,
>        height: 480,
>     
>        searchFieldHintText: "Search Here",
>        choiceChipLabel: (item) {
>           return item!.status;
>         },
>        validateSelectedItem: (list, val) {
>           return list!.contains(val);
>        },
>        onApplyButtonClick: (list) {
>           widget.product.forEach((element) {
>              if (list.any((model) => model.status == element.status)) {
>                selectedUserList.add(element);
>              }
>             });
>           setState(() {  });
>            // Navigator.pop(context);
>         },
> 
>        /// uncomment below code to create custom choice chip
>        choiceChipBuilder: (context, item, isSelected) {
>           return Container(
>              padding: EdgeInsets.symmetric(
>                  horizontal: MySize.size10, vertical: MySize.size10),
>              margin: EdgeInsets.symmetric(
>                  horizontal: MySize.size10, vertical: MySize.size10),
>              decoration: BoxDecoration(
>                borderRadius: BorderRadius.all(Radius.circular(MySize.size3!)),
>                   color: isSelected!
>                     ? Theme.of(context).colorScheme.primary
>                     : Theme.of(context).disabledColor,
>                ),
>               child: Text(
>                 item!.status,
>                  style:
>                   AppTheme.getTextStyle(Theme.of(context).textTheme.subtitle2),
>             ));
>        },
>     );
>   }
> ```

This will display only unique status in filter dialog box when you make some selection then it will display all those products having selected status. It won't remove the products from the list that you are displaying.

**Comment by AathifMahir** [comment]
@TheAlphamerc But, it removes the product as well

**Comment by TheAlphamerc** [comment]
Have you tried the code ?

**Comment by AathifMahir** [comment]
Yes, i have tried that code, Give me sec i'll share the code

**Comment by AathifMahir** [comment]
late List<ProductModel> selectedUserList = [];

  void _openFilterDialog() async {
    List<ProductModel> list = widget.product;

    var uniqueList = list.map((e) => e.status).toSet();

    /// Remove duplicate products having same uniqueTempList
    list.retainWhere((x) => uniqueList.remove(x.status));

    /// List of all selected products
    List<ProductModel> tempSelectedList = selectedUserList;

    if (selectedUserList != null && selectedUserList.isNotEmpty) {
      var uniqueTempList = tempSelectedList.map((e) => e.status).toSet();

      /// Remove duplicate selected products having same
      tempSelectedList.retainWhere((x) => uniqueTempList.remove(x.status));
    }

    await FilterListDialog.display<ProductModel>(
      context,
      listData: list,
      selectedListData: tempSelectedList,
      height: 480,
      // headlineText: "Select Users",
      searchFieldHintText: "Search Here",
      choiceChipLabel: (item) {
        return item!.status;
      },
      hideCloseIcon: true,
      hideheader: true,
      hideHeaderText: true,
      hideSearchField: true,
      backgroundColor: Theme.of(context).colorScheme.background,
      applyButonTextBackgroundColor: Theme.of(context).colorScheme.primary,
      selectedTextBackgroundColor: Theme.of(context).colorScheme.primary,
      borderRadius: MySize.size5!,
      controlButtonTextStyle: Theme.of(context).textTheme.subtitle2,
      applyButtonTextStyle: Theme.of(context).textTheme.subtitle2,
      unselectedTextbackGroundColor: Theme.of(context).disabledColor,
      controlContainerDecoration: BoxDecoration(
          borderRadius: BorderRadius.all(Radius.circular(MySize.size3!))),
      // buttonRadius: MySize.size5!,
      validateSelectedItem: (list, val) {
        return list!.contains(val);
      },

      onItemSearch: (list, text) {
        if (list != null) {
          if (list.any((element) =>
              element.status!.toLowerCase().contains(text.toLowerCase()))) {
            /// return list which contains matches
            return list
                .where((element) =>
                    element.status!.toLowerCase().contains(text.toLowerCase()))
                .toList();
          }
        }

        return [];
      },

      onApplyButtonClick: (list) {
        widget.product.forEach((element) {
          if (list!.any((model) => model.status == element.status)) {
            selectedUserList.add(element);
          }
        });
        // setState(() {  });
        setState(() {
          selectedUserList = List.from(list!);
        });
        // Navigator.pop(context);
      },

      /// uncomment below code to create custom choice chip
      choiceChipBuilder: (context, item, isSelected) {
        // return Container(
        //   padding: EdgeInsets.symmetric(horizontal: 16, vertical: 12),
        //   margin: EdgeInsets.symmetric(horizontal: 10, vertical: 10),
        //   decoration: BoxDecoration(
        //       border: Border.all(
        //     color: isSelected! ? Colors.blue[300]! : Colors.grey[300]!,
        //   )),
        //   child: Text(
        //     item.status,
        //     style: TextStyle(
        //         color: isSelected ? Colors.blue[300] : Colors.grey[300]),
        //   ),
        // );
        return Container(
            padding: EdgeInsets.symmetric(
                horizontal: MySize.size10, vertical: MySize.size10),
            margin: EdgeInsets.symmetric(
                horizontal: MySize.size10, vertical: MySize.size10),
            decoration: BoxDecoration(
              borderRadius: BorderRadius.all(Radius.circular(MySize.size3!)),
              color: isSelected!
                  ? Theme.of(context).colorScheme.primary
                  : Theme.of(context).disabledColor,
            ),
            child: Text(
              item!.status,
              style:
                  AppTheme.getTextStyle(Theme.of(context).textTheme.subtitle2),
            ));
      },
    );
  }

Only 2 products were showing since all the duplicates in the choice chips were removed, there should be around 7 to products totally

![Screenshot 2021-06-22 183759](https://user-images.githubusercontent.com/17165402/122930009-30f0cd80-d389-11eb-9db1-9f02bb36c315.png)
![Screenshot 2021-06-22 183813](https://user-images.githubusercontent.com/17165402/122930014-33ebbe00-d389-11eb-9939-1ecd7d3a89b3.png)

**Comment by TheAlphamerc** [comment]
Try replacing below code
```dart
    /// List of all products
    List<ProductModel> list = widget.product;
```

With 
```
 /// List of all products
    List<ProductModel> list = List.from(widget.product);
```

**Comment by AathifMahir** [comment]
> Try replacing below code
> 
> ```dart
>     /// List of all products
>     List<ProductModel> list = widget.product;
> ```
> 
> With
> 
> ```
>  /// List of all products
>     List<ProductModel> list = List.from(widget.product);
> ```

Still the same, still showing only 2 products

**Comment by TheAlphamerc** [comment]
Try replacing below code
```dart
 onApplyButtonClick: (list) {
    widget.product.forEach((element) {
      if (list!.any((model) => model.status == element.status)) {
        selectedUserList.add(element);
      }
    });
    // setState(() {  });
    setState(() {
      selectedUserList = List.from(list!);
    });
    // Navigator.pop(context);
  },
```

with 
```dart
 onApplyButtonClick: (list) {
      if(selectedUserList == null){
         selectedUserList = [];
        }
          widget.product.forEach((element) {
             if (list.any((model) => model.status == element.status)) {
               selectedUserList.add(element);
             }
            });
          setState(() {  });
           // Navigator.pop(context);
        },

```

**Comment by AathifMahir** [comment]
@TheAlphamerc Everything seems to working fine except top 2 products, 

here's the code

late List<ProductModel> selectedUserList = List.from(widget.product);

  void _openFilterDialog() async {
    List<ProductModel> list = List.from(widget.product);

    var uniqueList = list.map((e) => e.status).toSet();

    /// Remove duplicate products having same uniqueTempList
    list.retainWhere((x) => uniqueList.remove(x.status));

    /// List of all selected products
    List<ProductModel> tempSelectedList = selectedUserList;

    if (selectedUserList != null && selectedUserList.isNotEmpty) {
      var uniqueTempList = tempSelectedList.map((e) => e.status).toSet();

      /// Remove duplicate selected products having same
      tempSelectedList.retainWhere((x) => uniqueTempList.remove(x.status));
    }

    await FilterListDialog.display<ProductModel>(
      context,
      listData: list,
      selectedListData: tempSelectedList,
      height: 480,
      // headlineText: "Select Users",
      searchFieldHintText: "Search Here",
      choiceChipLabel: (item) {
        return item!.status;
      },
      hideCloseIcon: true,
      hideheader: true,
      hideHeaderText: true,
      hideSearchField: true,
      backgroundColor: Theme.of(context).colorScheme.background,
      applyButonTextBackgroundColor: Theme.of(context).colorScheme.primary,
      selectedTextBackgroundColor: Theme.of(context).colorScheme.primary,
      borderRadius: MySize.size5!,
      controlButtonTextStyle: Theme.of(context).textTheme.subtitle2,
      applyButtonTextStyle: Theme.of(context).textTheme.subtitle2,
      unselectedTextbackGroundColor: Theme.of(context).disabledColor,
      controlContainerDecoration: BoxDecoration(
          borderRadius: BorderRadius.all(Radius.circular(MySize.size3!))),
      // buttonRadius: MySize.size5!,
      validateSelectedItem: (list, val) {
        return list!.contains(val);
      },

      onItemSearch: (list, text) {
        if (list != null) {
          if (list.any((element) =>
              element.status!.toLowerCase().contains(text.toLowerCase()))) {
            /// return list which contains matches
            return list
                .where((element) =>
                    element.status!.toLowerCase().contains(text.toLowerCase()))
                .toList();
          }
        }

        return [];
      },

      onApplyButtonClick: (list) {
        if (selectedUserList == null) {
          selectedUserList = [];
        } else {
          widget.product.forEach((element) {
            if (list!.any((model) => model.status == element.status)) {
              selectedUserList.add(element);
            }
          });
        }
        setState(() {
          selectedUserList = List.from(selectedUserList);
        });
      },

      /// uncomment below code to create custom choice chip
      choiceChipBuilder: (context, item, isSelected) {
        // return Container(
        //   padding: EdgeInsets.symmetric(horizontal: 16, vertical: 12),
        //   margin: EdgeInsets.symmetric(horizontal: 10, vertical: 10),
        //   decoration: BoxDecoration(
        //       border: Border.all(
        //     color: isSelected! ? Colors.blue[300]! : Colors.grey[300]!,
        //   )),
        //   child: Text(
        //     item.status,
        //     style: TextStyle(
        //         color: isSelected ? Colors.blue[300] : Colors.grey[300]),
        //   ),
        // );
        return Container(
            padding: EdgeInsets.symmetric(
                horizontal: MySize.size10, vertical: MySize.size10),
            margin: EdgeInsets.symmetric(
                horizontal: MySize.size10, vertical: MySize.size10),
            decoration: BoxDecoration(
              borderRadius: BorderRadius.all(Radius.circular(MySize.size3!)),
              color: isSelected!
                  ? Theme.of(context).colorScheme.primary
                  : Theme.of(context).disabledColor,
            ),
            child: Text(
              item!.status,
              style:
                  AppTheme.getTextStyle(Theme.of(context).textTheme.subtitle2),
            ));
      },
    );
  }


here's demo video:


https://user-images.githubusercontent.com/17165402/122938488-6e0c8e00-d390-11eb-9964-4b7ec886dd52.mp4

**Comment by TheAlphamerc** [comment]
I think we need to handle a case where `onApplyButtonClick` callback returns empty or null list. 

Try replacing below code
```dart
 onApplyButtonClick: (list) {
    widget.product.forEach((element) {
      if (list!.any((model) => model.status == element.status)) {
        selectedUserList.add(element);
      }
    });
    // setState(() {  });
    setState(() {
      selectedUserList = List.from(list!);
    });
    // Navigator.pop(context);
  },
```

with 
```dart
 onApplyButtonClick: (list) {
      if(selectedUserList == null){
         selectedUserList = [];
        }
          widget.product.forEach((element) {
             if (list.any((model) => model.status == element.status)) {
               selectedUserList.add(element);
             }
            });
          setState(() {  });
           // Navigator.pop(context);
        },

```

**Comment by TheAlphamerc** [comment]
We need to handle a case where `onApplyButtonClick` returns empty or null list.

Try replacing below code
```dart
 onApplyButtonClick: (list) {
    widget.product.forEach((element) {
      if (list!.any((model) => model.status == element.status)) {
        selectedUserList.add(element);
      }
    });
    // setState(() {  });
    setState(() {
      selectedUserList = List.from(list!);
    });
    // Navigator.pop(context);
  },
```

with 
```dart
 onApplyButtonClick: (list) {
  if(!(list != null && list.isNotEmpty)){
    
      setState(() {
          selectedUserList = []; /// Now we have assigned null value to `selectedUserList` then you have to add null check value in ui where `selectedUserList` is used.
       });
      return;
   }
     if (selectedUserList == null) {
      selectedUserList = [];
    } else {
      widget.product.forEach((element) {
        if (list!.any((model) => model.status == element.status)) {
          selectedUserList.add(element);
        }
      });
    }
    setState(() {
      selectedUserList = List.from(selectedUserList);
    });
  },

```

**Comment by AathifMahir** [comment]
@TheAlphamerc Fixed the issue, Thanks a lot for help

here's complete code:

late List<ProductModel> selectedUserList = List.from(widget.product);

  void _openFilterDialog() async {
    List<ProductModel> list = List.from(widget.product);

    debugPrint("Data List: ${list.toString()}");

    var uniqueList = list.map((e) => e.status).toSet();

    /// Remove duplicate products having same uniqueTempList
    list.retainWhere((x) => uniqueList.remove(x.status));

    /// List of all selected products
    List<ProductModel> tempSelectedList = selectedUserList;

    if (selectedUserList != null && selectedUserList.isNotEmpty) {
      var uniqueTempList = tempSelectedList.map((e) => e.status).toSet();

      /// Remove duplicate selected products having same
      tempSelectedList.retainWhere((x) => uniqueTempList.remove(x.status));
    }

    await FilterListDialog.display<ProductModel>(
      context,
      listData: list,
      selectedListData: tempSelectedList,
      height: 480,
      // headlineText: "Select Users",
      searchFieldHintText: "Search Here",
      choiceChipLabel: (item) {
        return item!.status;
      },
      hideCloseIcon: true,
      hideheader: true,
      hideHeaderText: true,
      hideSearchField: true,
      backgroundColor: Theme.of(context).colorScheme.background,
      applyButonTextBackgroundColor: Theme.of(context).colorScheme.primary,
      selectedTextBackgroundColor: Theme.of(context).colorScheme.primary,
      borderRadius: MySize.size5!,
      controlButtonTextStyle: Theme.of(context).textTheme.subtitle2,
      applyButtonTextStyle: Theme.of(context).textTheme.subtitle2,
      unselectedTextbackGroundColor: Theme.of(context).disabledColor,
      controlContainerDecoration: BoxDecoration(
          borderRadius: BorderRadius.all(Radius.circular(MySize.size3!))),
      // buttonRadius: MySize.size5!,
      validateSelectedItem: (list, val) {
        return list!.contains(val);
      },

      onItemSearch: (list, text) {
        if (list != null) {
          if (list.any((element) =>
              element.status!.toLowerCase().contains(text.toLowerCase()))) {
            /// return list which contains matches
            return list
                .where((element) =>
                    element.status!.toLowerCase().contains(text.toLowerCase()))
                .toList();
          }
        }

        return [];
      },

      onApplyButtonClick: (list) {
        if (!(list != null && list.isNotEmpty)) {
          setState(() {
            selectedUserList = [];
            list = [];

            /// Now we have assigned null value to `selectedUserList` then you have to add null check value in ui where `selectedUserList` is used.
          });
          return;
        }
        if (selectedUserList == null || list == null) {
          setState(() {
            selectedUserList = [];
            list = [];
          });
        } else {
          // for(var element in widget.product){
          //   if (list.any((model) => model.status == element.status)) {
          //     selectedUserList.add(element);
          //   }
          // }
          widget.product.forEach((element) {
            if (list!.any((model) => model.status == element.status)) {
              debugPrint("Elements: ${element.status}");
              selectedUserList.add(element);
              if (list!.contains(element) != true) {
                list!.add(element);
              }
            }
          });
        }
        setState(() {
          selectedUserList = List.from(list!);
        });
        //
        // if (selectedUserList == null) {
        //   selectedUserList = [];
        // } else {
        //   widget.product.forEach((element) {
        //     if (list!.any((model) => model.status == element.status)) {
        //       selectedUserList.add(element);
        //     }
        //   });
        // }
        // setState(() {
        //   selectedUserList = List.from(selectedUserList);
        // });
      },

      /// uncomment below code to create custom choice chip
      choiceChipBuilder: (context, item, isSelected) {
        // return Container(
        //   padding: EdgeInsets.symmetric(horizontal: 16, vertical: 12),
        //   margin: EdgeInsets.symmetric(horizontal: 10, vertical: 10),
        //   decoration: BoxDecoration(
        //       border: Border.all(
        //     color: isSelected! ? Colors.blue[300]! : Colors.grey[300]!,
        //   )),
        //   child: Text(
        //     item.status,
        //     style: TextStyle(
        //         color: isSelected ? Colors.blue[300] : Colors.grey[300]),
        //   ),
        // );
        return Container(
            padding: EdgeInsets.symmetric(
                horizontal: MySize.size10, vertical: MySize.size10),
            margin: EdgeInsets.symmetric(
                horizontal: MySize.size10, vertical: MySize.size10),
            decoration: BoxDecoration(
              borderRadius: BorderRadius.all(Radius.circular(MySize.size3!)),
              color: isSelected!
                  ? Theme.of(context).colorScheme.primary
                  : Theme.of(context).disabledColor,
            ),
            child: Text(
              item!.status,
              style:
                  AppTheme.getTextStyle(Theme.of(context).textTheme.subtitle2),
            ));
      },
    );
  }

**Comment by TheAlphamerc** [comment]
@AathifMahir Now you understand Why I was saying that you can remove duplicate values after passing to the sdk.

**Comment by AathifMahir** [comment]
@TheAlphamerc I think it would be great that if this merging duplicate items in choicechip would be built into filter_list module as boolean value to enable or disable merging duplicate choicechip items
